### ISSUE TITLE
Great theme! Comments are very hard to read.

### ISSUE THREAD

**Issue by mikesigs** [PeterShershov/blueberry-banana-vscode-theme#1]
![image](https://user-images.githubusercontent.com/811177/63061494-984ab600-beb2-11e9-9d0b-3e5997d9f31e.png)

You can even see the comments being super dark in your own screenshot.
![image](https://user-images.githubusercontent.com/811177/63061514-a8fb2c00-beb2-11e9-8502-1d9b6eb00743.png)

Other than this, the theme is beautiful. Thank you!

**Comment by PeterShershov** [comment]
fixed and published 👍  
thanks!

**Comment by mikesigs** [comment]
Wham bam! Thank you man! haha
