### ISSUE TITLE
Compatibility with vs code 1.36.1

### ISSUE THREAD

**Issue by AmauryOrtega** [PeterShershov/blueberry-banana-vscode-theme#2]
## Information

- VS Code version `1.36.1`

I can upgrade VS Code to version `1.37.0` if this solves the issue. If this is the reason, is it possible to add a compatibility section in the description of the extension in the marketplace?

## Error message

```
Unable to install 'pshershov.blueberry-banana' extension because it is not compatible with the current version of VS Code (version 1.36.1).
```

**Comment by PeterShershov** [comment]
Hey @AmauryOrtega , thanks for opening an issue!
I changed the `engines` field in `package.json` to support older versions of vscode.
You can try again now :)

**Comment by AmauryOrtega** [comment]
@PeterShershov Thanks! Now it works perfectly.
