### ISSUE TITLE
Text's color is the same as the element's color

### ISSUE THREAD

**Issue by Ayman97** [PeterShershov/blueberry-banana-vscode-theme#3]
Hey
The text's color is the same as the element's color in jsx elements. Can you fix it?

![image](https://user-images.githubusercontent.com/10719494/66575988-38515280-eb77-11e9-9d34-ad7d8537031f.png)

**Comment by PeterShershov** [comment]
Hey @Ayman97, thanks for the issue.
`jsx` / `tsx` element's string children now have the same color as HTML children in `html` file.
 
Please update the extension :)

**Comment by Ayman97** [comment]
@PeterShershov  Thanks a lot!
