### ISSUE TITLE
iTerm 2 Theme

### ISSUE THREAD

**Issue by ReagentX** [PeterShershov/blueberry-banana-vscode-theme#4]
I created an iTerm 2 theme based on this color scheme:

https://gist.github.com/ReagentX/44232d26f98e78805fd4326dfd1bca46

![image](https://user-images.githubusercontent.com/1920666/73774598-40e71d80-4752-11ea-9915-55550d9e3001.png)

**Comment by PeterShershov** [comment]
Awesome! Thanks for letting me know 😊
