### ISSUE TITLE
open-vsx.org

### ISSUE THREAD

**Issue by zzzspawn** [PeterShershov/blueberry-banana-vscode-theme#5]
Hello, I was wondering if you might be able to add this to open-vsx.org as well? I prefer to use vscodium when I can, and then I can't really use this great color scheme (which I wish existed for jetbrains products as well 😅) 😢

That is all! thank you very much for thinking up this set of colors; and creating the theme, I don't use vscode too often these days, but everytime I need to install it I keep coming back to this theme 😍

**Comment by PeterShershov** [comment]
Hey @zzzspawn, 
First off, thanks for the kind words - it means a lot to me.
[Here's](https://open-vsx.org/extension/pshershov/blueberry-banana) the published version (the namespace will be verified soon).
I have tested it on **vscodium** and it seems to be working fine, I am closing this issue for now but please let me know if any issues arise.

Thanks again 🙏 

P.S
I will take a look into getting this into **Intellij**, **Webstorm** and other **Jetbrains** code editors. This will probably require some adaptations and changes. 
I will update this repo whenever this gets done.
