### ISSUE TITLE
Buttons for installing extensions have low contrast to background

### ISSUE THREAD

**Issue by goodideagiver** [PeterShershov/blueberry-banana-vscode-theme#6]
## Screen of the issue:
![obraz](https://user-images.githubusercontent.com/55458485/188596128-decf4899-5c69-4667-a808-644a9b55bae8.png)

## Current colors contrast: 
via [Adobe color](https://color.adobe.com/create/color-contrast-analyzer):
![obraz](https://user-images.githubusercontent.com/55458485/188596431-8a742416-ae34-4ba7-82d3-9c1f7197f763.png)

## Preferred color contrast:
![obraz](https://user-images.githubusercontent.com/55458485/188596675-33282379-5a6b-415c-96f2-12dac00149fd.png)

## Button color on the second example is picked from file/source/find icon on VSC sidebar. It still doesn't fulfill adobe contrast check, but I think white text should be enough of an indicator.
![obraz](https://user-images.githubusercontent.com/55458485/188597106-9cb129a8-f2e4-4ad6-a80d-0f9ac0be5604.png)

## Why I think this should be implemented?
It's hard to manage/install extensions because clicking buttons is harder, It's very hard to see the edges of buttons.

By the way: I like this theme very much, great job!

**Comment by goodideagiver** [comment]
How it looks:
![obraz](https://user-images.githubusercontent.com/55458485/188600237-154d5f3f-8573-4ba6-8f85-c459281a62a9.png)

The settings are:
`"extensionButton.prominentBackground": "#4c3552",
"extensionButton.prominentHoverBackground": "#6a4a72",`

I don't know what the ones on extension main page are called.

**Comment by PeterShershov** [comment]
Hey, thanks for opening the issue.
I've just published a version including a slight color change to this background, making it distinctive but still accessible:
<img width="583" alt="image" src="https://user-images.githubusercontent.com/16524839/188938064-4af86e10-9bb8-41e7-9762-2317ef198fb5.png">

<img width="658" alt="image" src="https://user-images.githubusercontent.com/16524839/188938096-12d6f585-62cb-4941-9764-738dd0ca6607.png">

<img width="623" alt="image" src="https://user-images.githubusercontent.com/16524839/188938139-999b5954-38ce-4682-9df4-a659cc5345c5.png">
