### ISSUE TITLE
Blueberry Banana for WebStorm

### ISSUE THREAD

**Issue by Nirwana3301** [PeterShershov/blueberry-banana-vscode-theme#7]
Dear Peter Shershov,

I've been a fan of your VS Code theme for almost three years now. I'm currently transitioning to the WebStorm IDE by JetBrains, and I was wondering if it's possible to obtain the same theme for WebStorm.

With kind regards,
Anton

**Comment by PeterShershov** [comment]
Hey, sorry for the delayed answer and thanks for opening this issue🙏 
I've started to work on supporting Webstorm and I will surely update once it'll be ready.
Thanks again

**Comment by Nirwana3301** [comment]
Is there anything new on this topic? When will the theme be available? @PeterShershov

**Comment by PeterShershov** [comment]
@Nirwana3301 thanks for asking, much appreciated. As I mentioned previously I started to work on it but had an issue with the license. This will be resolved soon, and I'll update once it's out.
